#!/bin/sh

#description "Automatic Backlight Adjustment"
#author "Ryan Brackkenbury ryan.brackenbury@gmail.com"

# This is just a stub for starting the service. Definitely are better solutions,
# but this is simple and should work on all UNIX-like systems

PIDFILE="/tmp/autolight.pid"            # Path to where pid should be stored. 
USER="nobody"                           # Do not run as root
BINPATH="/usr/bin/autolight"            # Path to bin or bin name

if [ `whoami` != "root" ]; then
    echo "Script must be run as root. Usage: $0 {start|stop}"
    exit 1
fi

case "$1" in
  start)
    if [ -e $PIDFILE ]; then
      echo "Autolight already running!"
    else
      echo "Starting autolight"
      nohup su $USER -c "exec $BINPATH" &
      echo -n $! > $PIDFILE
    fi
    ;;
  stop)
    echo "Stopping autolight"
    if [ -e $PIDFILE ]; then
      kill -9 `cat $PIDFILE`
      rm -f $PIDFILE
    fi 
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
