#!/bin/sh

#description "Automatic Backlight Adjustment"
#author "Ryan Brackkenbury ryan.brackenbury@gmail.com"

# This is just a stub for starting the service. Definitely are better solutions,
# but this is simple and should work on all UNIX-like systems

PIDFILE="/tmp/delux.pid"            # Path to where pid should be stored. 
USER="root"                           # Default user is root (permissions issue)
BINPATH="/usr/sbin/delux"            # Path to bin OR bin name

if [ `whoami` != "root" ]; then
    echo "Script must be run as root. Usage: $0 {start|stop}"
    exit 1
fi

case "$1" in
  start)
    if [ -e $PIDFILE ]; then
      echo "Delux already running!"
    else
      echo "Starting delux"
      nohup su $USER -s /bin/sh -c "exec $BINPATH" &
      echo -n $! > $PIDFILE
    fi
    ;;
  stop)
    echo "Stopping delux"
    if [ -e $PIDFILE ]; then
      kill -15 `cat $PIDFILE`
      rm -f $PIDFILE
    fi 
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
